/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InspectorRouteImport } from './routes/inspector'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as GuardrailsRouteImport } from './routes/guardrails'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ApiKeysRouteImport } from './routes/api-keys'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectorRoute = InspectorRouteImport.update({
  id: '/inspector',
  path: '/inspector',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardrailsRoute = GuardrailsRouteImport.update({
  id: '/guardrails',
  path: '/guardrails',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/api-keys': typeof ApiKeysRoute
  '/dashboard': typeof DashboardRoute
  '/guardrails': typeof GuardrailsRoute
  '/history': typeof HistoryRoute
  '/inspector': typeof InspectorRoute
  '/login': typeof LoginRoute
  '/monitoring': typeof MonitoringRoute
  '/playground': typeof PlaygroundRoute
  '/settings': typeof SettingsRoute
  '/usage': typeof UsageRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/api-keys': typeof ApiKeysRoute
  '/dashboard': typeof DashboardRoute
  '/guardrails': typeof GuardrailsRoute
  '/history': typeof HistoryRoute
  '/inspector': typeof InspectorRoute
  '/login': typeof LoginRoute
  '/monitoring': typeof MonitoringRoute
  '/playground': typeof PlaygroundRoute
  '/settings': typeof SettingsRoute
  '/usage': typeof UsageRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/api-keys': typeof ApiKeysRoute
  '/dashboard': typeof DashboardRoute
  '/guardrails': typeof GuardrailsRoute
  '/history': typeof HistoryRoute
  '/inspector': typeof InspectorRoute
  '/login': typeof LoginRoute
  '/monitoring': typeof MonitoringRoute
  '/playground': typeof PlaygroundRoute
  '/settings': typeof SettingsRoute
  '/usage': typeof UsageRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/api-keys'
    | '/dashboard'
    | '/guardrails'
    | '/history'
    | '/inspector'
    | '/login'
    | '/monitoring'
    | '/playground'
    | '/settings'
    | '/usage'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/api-keys'
    | '/dashboard'
    | '/guardrails'
    | '/history'
    | '/inspector'
    | '/login'
    | '/monitoring'
    | '/playground'
    | '/settings'
    | '/usage'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/api-keys'
    | '/dashboard'
    | '/guardrails'
    | '/history'
    | '/inspector'
    | '/login'
    | '/monitoring'
    | '/playground'
    | '/settings'
    | '/usage'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  ApiKeysRoute: typeof ApiKeysRoute
  DashboardRoute: typeof DashboardRoute
  GuardrailsRoute: typeof GuardrailsRoute
  HistoryRoute: typeof HistoryRoute
  InspectorRoute: typeof InspectorRoute
  LoginRoute: typeof LoginRoute
  MonitoringRoute: typeof MonitoringRoute
  PlaygroundRoute: typeof PlaygroundRoute
  SettingsRoute: typeof SettingsRoute
  UsageRoute: typeof UsageRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspector': {
      id: '/inspector'
      path: '/inspector'
      fullPath: '/inspector'
      preLoaderRoute: typeof InspectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardrails': {
      id: '/guardrails'
      path: '/guardrails'
      fullPath: '/guardrails'
      preLoaderRoute: typeof GuardrailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-keys': {
      id: '/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  ApiKeysRoute: ApiKeysRoute,
  DashboardRoute: DashboardRoute,
  GuardrailsRoute: GuardrailsRoute,
  HistoryRoute: HistoryRoute,
  InspectorRoute: InspectorRoute,
  LoginRoute: LoginRoute,
  MonitoringRoute: MonitoringRoute,
  PlaygroundRoute: PlaygroundRoute,
  SettingsRoute: SettingsRoute,
  UsageRoute: UsageRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
